[versions]
minecraft = "1.8.9"
mixin = "0.11.4+mixin.0.8.5"
gson = "2.10.1"
yarn = "1.8.9+build.456"
hypixel_api = "4.0"
discord_game_sdk4j = "v0.5.4"
java_websocket = "1.5.3"
cosmetica_dot_java = "1.7.0"
lwjgl_patched = "bf1d105853"
lwjgl = "3.3.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
yarn = { module = "net.legacyfabric:yarn", version.ref = "yarn" }
hypixel_api = { module = "net.hypixel:hypixel-api-core", version.ref = "hypixel_api" }
discord_game_sdk4j = { module = "com.github.JnCrMx:discord-game-sdk4j", version.ref = "discord_game_sdk4j" }
java_websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java_websocket" }
cosmetica_dot_java = { module = "com.github.Cosmetica-cc:CosmeticaDotJava", version.ref = "cosmetica_dot_java" }
lwjgl_patched = { module = "com.github.Sol-Client:lwjgl-patched", version.ref = "lwjgl_patched" }
lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl_nanovg = { module = "org.lwjgl:lwjgl-nanovg", version.ref = "lwjgl" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }
lombok = { id = "io.freefair.lombok", version = "6.6.1" }